### ISSUE TITLE
Feature Request: Checkboard Background for Transpencies

### ISSUE THREAD

**Issue by lehitoskin** [chandevel/Clover#286]
Images with transparent backgrounds should probably have a checkerboard. Dark images with a dark theme make for poor viewing.

**Comment by jayexxd** [comment]
Would be nice to add an option for a colored background (mainly white) like on the main site.

**Comment by Adamantcheese** [comment]
I've been hard at work, and submitted 8 pull requests. While Floens and other maintainers work on adding them in, if ever, [you can find a debug multi-release of all the features from my pulls here.](https://github.com/Adamantcheese/Clover/releases)
