### ISSUE TITLE
ES Explorer crashes Clover

### ISSUE THREAD

**Issue by Ockaie** [chandevel/Clover#308]
When choosing an image with ES explorer for a new thread or post Clover crashes. You can browse to the image but when you choose the image and go back to Clover it crashes. When using anything else it doesn't​.

Steps to reproduce:
Step 1. Start a thread
Step 2. Press image button
Step 3. Choose ES Explorer as method of browsing and selecting an image
Step 4. Select image
Step 5. Crash

Android version: 6.0.1
Phone model: Nexus 5
Clover version: v2.3.0 F-Droid

**Comment by Dizor** [comment]
Having a similar problem with es, Dropbox and quick pic. Running the latest clover didn't fix it, using a Nexus 5 running Android 6.0.1

**Comment by hash-dev** [comment]
I don't remember the version of ES I used at the time, but versions around that time work with Clover v3.0.2.
