### ISSUE TITLE
Cache mode/offline content

### ISSUE THREAD

**Issue by pindogu** [chandevel/Clover#330]
Would be cool if you could add a toggle for a "cache mode" to the options so that pinned threads get saved for offline reading.

I already love your app and that would make it a lot better for me since i dont always have an internet connection.

**Comment by bytegeist** [comment]
Seconded, the ability to save and archive threads would be huge, but that's a rather advanced and work intensive feature.

**Comment by Floens** [comment]
This is actually a very old request. #172 is almost the same.
