### ISSUE TITLE
[Suggestion] Automatic day/night switching for themes

### ISSUE THREAD

**Issue by gatosardina** [chandevel/Clover#333]
Scheduler to change the app them depending on the hour of the day. Useful to set a light theme for the day and a dark on for the night

**Comment by nilesr** [comment]
Currently changing the theme calls finish() then recreates the activity. This discards the saved instance state. If the scheduler updated while you were browsing a thread, you would be randomly reset back to the board screen and lose whatever you were working on or typing. 

However, it could potentially be checked at app start

**Comment by gatosardina** [comment]
I've thought on this and maybe add a pop up dialogue that prompts you to restart the app to change theme?
If you are using the app and the scheduler updated, app wouldn't change theme until next app restart
Dialogue pop up can be turned on or off in settings
Maybe add a toast notification "theme will update on app restart"

**Comment by azumukupoe** [comment]
Dark mode integration?
