### ISSUE TITLE
[Feature] Add Filter option to notify you when thread is made matching filter

### ISSUE THREAD

**Issue by Tenome** [chandevel/Clover#362]
Not sure if this would really work, since it requires Clover to constantly refresh the catalog. But it'd be nice to be notified when a thread matching your filter is made.

**Comment by Adamantcheese** [comment]
[I've added that feature in the fork I pulled off. I've submitted a pull request but I dunno if it'll be added in. You can always build it and side load it yourself if you want.](https://github.com/Adamantcheese/Clover)
[The pull request can be found here.](https://github.com/Floens/Clover/pull/627)

**Comment by Adamantcheese** [comment]
I've been hard at work, and submitted 8 pull requests. While Floens and other maintainers work on adding them in, if ever, [you can find a debug multi-release of all the features from my pulls here.](https://github.com/Adamantcheese/Clover/releases)
