### ISSUE TITLE
Add awoo board engine

### ISSUE THREAD

**Issue by gatosardina** [chandevel/Clover#383]
Plz floens
https://github.com/dangeru/awoo

**Comment by Floens** [comment]
Do you have the following:
API documentation
what features does it support / should clover support

also see #263

**Comment by gatosardina** [comment]
trying to get this from the awoo devs
what exactly do you mean with features?
right now the boards has IDs, >quote text, >>post quotation and a thread watcher
more features are on the work like coloured text and attaching images to posts
there are 2 test boards, one fo them is an image-only board where you have to choose between 2 preselected images and decide which to post, and a more general engine testing board with experimental features

**Comment by gatosardina** [comment]
this was their response:
` ##Dev:Lain##

Post number #137143, ID: 054a9d
| Yes, we have an api documented here: https://github.com/dangeru/awoo-API

We also have a dashchan extension that uses that API. This isnt the latest version but it includes all the code that you'd need to receive/post threads/replies. https://github.com/dangeru/Dashchan-Extension

##Dev:Lain##

Post number #137144, ID: 054a9d
| Additionally, the code in here should be reusable with only slight refactoring.
https://github.com/nilesr/United4/tree/master/app/src/main/java/com/angryburg/uapp/API

Thread.java is a generic wrapper that simply accepts the JSON object that was returned from the server and sets its internal properties accordingly `
