### ISSUE TITLE
watched threads "unwatch" posts after new posts

### ISSUE THREAD

**Issue by gatosardina** [chandevel/Clover#408]
i'm on latest dev release and i'm having a bug where i keep a couple watched threads with all the posts already seen (past the red line and made it disappear by reaching full bottom)
i close the app and when a couple later i check it again and there are new posts on those threads, some of the last posts i had already seen become "unseen" (red line marking new posts is above them)
not only that but images that i had already downloaded for preview (not to device) have to redownload (and no i didnt clear cahce or anything)
i can easily spot those posts because of the post date
clover version: 2.3.1-c8554bc9
android 7.1.2

**Comment by Floens** [comment]
It saves the loadable state (what posts you've seen) when you put the app in the background. It might be that the app is killed too fast? Otherwise it's a bug.

>but images that i had already downloaded for preview (not to device) have to redownload (and no i didnt clear cahce or anything)

The cache has a limit, which means that images get purged from the cache if it gets too full.

**Comment by gatosardina** [comment]
i'll try to wait a bit longer but it'd be weird as i've been suing clover for 2 or 3 years and this hadn't happened before
shouldnt the cache be purged from older to newer?
would make sense if it purged the first images in the thread that were days old but instead the last ones were purged?

**Comment by Floens** [comment]
I think I sometimes have this issue too, not that I've been watching it. I'll try to figure out if this is a real issue before closing this issue.
