### ISSUE TITLE
Cannot get pass recaptcha verification that reqire copy and paste a code

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#411]
Recently, over an unstable internet connection, when I tries to make a post via clover, I was given a special kind of captcha that involve a text field and the regular captcha selection. After picking images like regular captchas, I was presented with a series of code that would be valid for 2 minutes, and then I was asked to copy it and paste the code into the textbox to comolete the verification. I used the android system build in functionality to copy and paste the box, but nothing happened thereafter and thus I can't get pass the check

Android version: 5.1
Phone model: Lenovo Tablet
Clover version: 2.3.1

**Comment by Floens** [comment]
That's weird  That's the no script recaptcha2, but it shouldn't appear in the place of the normal recaptcha2.

**Comment by c933103** [comment]
I am suspecting that the JavaScript file might not be able to complete loading due to the network environment problem and thus the noscript one turn up instead

**Comment by c933103** [comment]
hummm.... Now I am on a stable network instead of aforementioned instable network, and the stable 1.3.2 version Clover can get the normal captcha normally, but the dev version clover is now getting the noscript captcha. Any idea why that would happens?
