### ISSUE TITLE
Tabbing into Clover doesn't return you to your last location

### ISSUE THREAD

**Issue by Lunanite** [chandevel/Clover#480]
Since the last update, tabbing back into Clover from another app doesn't bring you to the last thread/board you were on, it just reloads the app at your home board. This is unhelpful when doing things such as tabbing out to look up things/copy links while typing a reply, as you have to navigate back to the thread every time.

On 3.0.0, Android Version 7.0

**Comment by anzetal** [comment]
Still persists in 3.0.1 fdriod. When I press home to check another app, it reloads again. It wasn't an issue in previous clover versions

**Comment by Floens** [comment]
It's an Android bug. If you keep pressing back until Clover is fully closed it will not do that anymore. I added a patch for this but apparently it doesn' t seem to work for F-Droid. I'll have another look.
