### ISSUE TITLE
[Request] Choose from available sites instead of entering URL

### ISSUE THREAD

**Issue by TheLastZombie** [chandevel/Clover#481]
So while I appreciate support for multiple sites, I think it would make much more sense to display a list of supported sites and let the user choose from them instead of forcing him/her to enter the site URL.

This would be much more convenient and faster, plus one could get an overview of which sites are supported and which aren't.

**Comment by Floens** [comment]
The current UI was done in mind with #264 and #263, although I agree that now it would be way more user-friendly to provide a list of sites we support, especially on non-play builds.
The url field is also meant to support sites that dynamically tell Clover what type of api they support, something that is not implemented yet.
