### ISSUE TITLE
Thread title not display correctly when making a thread

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#484]
Step to reproduce:
1. Make a thread
2. It automatically bookmarked
3. The text for bookmarked thread being shown consists of only numbers i.stead of thread title or thread text

Android version: 8.0.0
Phone model: XZ1c
Clover version: 3.0.0

**Comment by Adamantcheese** [comment]
Pull request #632 fixes this issue. Threads aren't loadable as soon as they're posted, so they'll have a default title of the board and OP post number until the thread is loadable. Once it is loaded again by the watch manager it'll update to the proper thread title. It shouldn't be more than 2 or 3 minutes before the thread is loadable and this is the easy, one line of code, eventually correct solution.

**Comment by Adamantcheese** [comment]
I've been hard at work, and submitted 8 pull requests. While Floens and other maintainers work on adding them in, if ever, [you can find a debug multi-release of all the features from my pulls here.](https://github.com/Adamantcheese/Clover/releases)
