### ISSUE TITLE
"Password incorrect when trying to delete a post

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#512]
Note: I don't usually encounter this error but from tines to tines it appears
Steps:
1. Make a reply in a thread
2. Click the delete button
3. Get warning: Password incorrect

Android version: 8.0.0
Phone model: XZ1 Compact
Clover version: 3.0.0

**Comment by c933103** [comment]
![screenshot_20180618-064011](https://user-images.githubusercontent.com/1525293/41512811-1533c4b4-72c3-11e8-9c51-c76c1a85a5ad.png)

**Comment by Astridchan** [comment]
Also getting this. Tried deleting the post through the browser and got a "something went wrong." message. Interestingly I have the same phone as OP.

Android version: 8.0.0
Phone model: XZ1 Compact
Clover version: 3.0.1-977c5a1f
