### ISSUE TITLE
Increase saved response table size limit

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#527]
1. Make a post on a longlasting thread in a slow board via clover
2. Using the phone and the app regularly for some months. In some instance the phone free storage might run down to 0MB available and thus might have triggered some behavior that would automatically clear something that I would not be aware of.
3. Check back on those threads after a few months
4. Own posts are not marked, replies to my own posts are not notifying me, and they do not show (you) when they're replying to posts made by mine.

Android version: 8.0.0
Phone model: XZ1 Compact
Clover version: v3.0.0, might affect earlier versions before upgrade too

**Comment by Floens** [comment]
How would I test / reproduce this?

**Comment by c933103** [comment]
Not sure how to. Maybe go to a very slow board on 4chan like /n/ or so and make a post in one of those longlasting threads via clover, then continuously using clover just like normal while having the phone low in memory, then check back in a few month's time?

**Comment by Floens** [comment]
Oh I just remembered, the history and savedreply (where the (you)s are stored) are automatically trimmed after a while. This is probably the issue. It is intended behavior. We could raise the limit.

**Comment by c933103** [comment]
Some threads on 4chan like https://boards.4chan.org/n/thread/1108903 can last more than a year (like in the example it was created last year but still only 1/3 the bump limit), not to mention other chans that may go even slower. I am not sure what the appropriate time period would be. What is the current time setting?

**Comment by Floens** [comment]
It counts the amount of rows in the table and trims it.
https://github.com/Floens/Clover/blob/dev/Clover/app/src/main/java/org/floens/chan/core/database/DatabaseSavedReplyManager.java#L43
It seems that it's currently on `250`, which is pretty low.

**Comment by c933103** [comment]
If someone make 100 posts a day on average then in three year that would be 100k record. It probably won't use too many space even with 100k record? But would it cause any performance constraint? As in some cases thread could be alive even after three years. Or how about not trimming records for threads that are still alive?

**Comment by Floens** [comment]
There is a limit because all data has to be loaded on startup, in order to make the check faster.

The app doesn't completely malfunction if a saved reply is gone after a long time.

I think raising the limit to ~10k would be good, but we'll have to check what the performance impact is.
