### ISSUE TITLE
Black screen after taking screenshot

### ISSUE THREAD

**Issue by manwalk** [chandevel/Clover#560]
Screen goes black after taking screenshot with solarized solor scheme

Just switched from gruvbox color scheme to solarized and taking a screenshot (power+volDown on moto x4) causes screen to turn black. Quitting out of clover fixes the issue until I take another screenshot. Issue only happens with solarized scheme.

Starting with gruvbox scheme applied: settings>appearance>theme>'Solarized Dark' Then take a screenshot

Android version: 8.0.0
Phone model: moto x4 
Clover version: Clover dev v3.0.1-977c5a1f

**Comment by alex-eyre** [comment]
I can't repeat this error, can you give more specific steps?
Android Version: 9.0.0
Phone: Xiaomi Mi Mix
Clover Version: Clover dev v3.0.1-977c5a1f
