### ISSUE TITLE
Request: Make is easier to display a board.

### ISSUE THREAD

**Issue by c933103** [chandevel/Clover#569]
Sometimes my mobile network connection is being throttled down to 128kbps (usable speed would be lower due to overheads), together with decreased service priority, and the result of that is it's pretty much impossible to load a board in clover app, as it seems like a relatively large amount of data would need to be loaded before a board can be opened.

Please try to make it easier to load a board. (or maybe increase time out to something like an hour?)

**Comment by c933103** [comment]
I have tried both but still not helping.

**Comment by notstevek** [comment]
maybe text only mode has an issue where maybe it still loads thumbnails or doesn't check for that text only mode on boot first, no clue, I don't know java. I tried testing it locally to see what my network would spike to on my Android but I don't have something giving me actual one time usage info, versus just what my network spikes to, so it was the same with media on and off, but not a good or reliable measure. maybe floens knows the issue or knows a fix.

**Comment by c933103** [comment]
And text only mode cannot load files on click
