### ISSUE TITLE
[Request] Ability to sort threads by activity (replies/minute) in catalog mode

### ISSUE THREAD

**Issue by happapa** [chandevel/Clover#583]
Similar to how https://4stats.io/ shows the most active threads. Sorting by bump order is not as useful.

**Comment by happapa** [comment]
> Pretty sure you need to inspect all threads repeatedly to get to those statistics.

Really? You would only need the creation time of each thread and the number of replies. And since you can already sort threads by creation time and the number of replies is visible in the catalog mode, I don't think any extra data would need to be scraped.

**Comment by Floens** [comment]
Ok that formula does work yes.
