### ISSUE TITLE
SFW boards are going to move to the 4channel.org domain

### ISSUE THREAD

**Issue by Gladuin** [chandevel/Clover#595]
I don't know if this is just a domain change or that 4channel.org is going to be a completely different website. Just a heads up.

![Announcement](https://user-images.githubusercontent.com/34450360/48664694-e6a56280-eaa2-11e8-8f01-02d45ed25199.jpg)

**Comment by Floens** [comment]
Thank you for the issue, I saw the announcement yes.

I don't expect the api to change. It's domain is a facade by Hiro to get more ad money ([source](https://boards.4chan.org/qa/thread/2421255#p2421509)).

**Comment by c933103** [comment]
When they start using different logo for each site, or stop allowing people from accessing all boards from either domain name, then the app should also treat that at two different sites when adding/removing sites/boards.

**Comment by Gladuin** [comment]
/qa/ is the only board that redirects to 4channel.org so far that I have found, and it still works on Clover

**Comment by c933103** [comment]
If I understand correctly, SFW boards now support posting emoji but only if user have switched to using new domain for posting? Is this an accurate description?

**Comment by Riotous** [comment]
@Floens It has begun
