### ISSUE TITLE
When attempting to post to 4chan.org Im told Im banned through Clover but I can post through browsers like chrome

### ISSUE THREAD

**Issue by nikoli90** [chandevel/Clover#603]
While attempting to post while using mobile data through clover I am given the ban error. This is only while posting to 4chan.org, when posting to 4channel it works just fine. However when using a browser I am able to post to both boards with no problem. Going to both /banned pages gives me a your not banned on 4chan/4channel readout
Im not entirely sure how to recreate the bug, although the issue is connected to the recent board split as that is when the error started. 

Android version: 8.0
Phone model: SM-G955U
Clover version: 3.0.1

**Comment by Nommly** [comment]
You have to accept the ban reasoning through the 4chan website before you get the approval to continue to post on 4chan

**Comment by ajtpak** [comment]
I'm getting this issue now too. 

When I go to the site on my desktop and post, I'm not banned. It only seems to be on clover that it thinks I'm banned. 

Even when I check my ban status, I'm not banned. Yet when I post specifically through clover,I get a ban error  

Android: 9.0
Phone: Pixel 3xl
Clover version: 3.0.1

**Comment by vinegarZombie** [comment]
If on the phone using mobile data close clover turn on airplane mode and turn it off. Start clover again and it will let you post.
