### ISSUE TITLE
Feature request: jump to next (you) 

### ISSUE THREAD

**Issue by observeroftime02** [chandevel/Clover#607]
[short and descriptive title]
Requesting the feature to jump to the next post mentioning you

[detailed explanation of the issue]
Sometimes in long threads it can be a challenge to find the posts quoting you. I'd have to scroll through and look for the backlink followed by (you) to identify who's quoting me, or scroll back to find my post and click on the reply count. 

Either a menu option to jump to the next poster quoting me or a real visual highlight cue of posts quoting me would be beneficial for usability.

**Comment by happapa** [comment]
I would prefer a similar hilighting you can already get for posts using filters. Sadly ">>XXXXXXX (You)" is not part of the message body, so you can't currently add a regex filter for it inside the app.

**Comment by WaywardSkylark** [comment]
A bit of a workaround I use is just searching for (you). It highlights replies well enough.
