### ISSUE TITLE
Webm seeking often not working

### ISSUE THREAD

**Issue by WaywardSkylark** [chandevel/Clover#610]
Seeking through webms usually just restarts the webm instead of going to the selected position, and long webms don't show length numbers - will show how far into the webm you are but won't show how long it is.

 Android 7.1.1 on Moto e4 Plus

Clover v3.0.1

**Comment by Adamantcheese** [comment]
This doesn't appear to be a problem anymore as the player was upgraded to exoplayer. If it is a problem still, please bring it up again.
