### ISSUE TITLE
4channel browser links not opening in app

### ISSUE THREAD

**Issue by Ashtonio** [chandevel/Clover#626]
Using "Open Link With" to open links when on 4chan work correctly, but when on 4channel it doesn't, I suspect that it may have something to do with the app setting "Supported web addresses" which show the 4chan links but not the 4channel links.

**Comment by Ashtonio** [comment]
"Open with an app" button when clicking on a link also only shows Clover when on 4chan but not 4channel.

**Comment by franchan1** [comment]
Dowload firefox Klar you will be able to open a link when lighting it.

**Comment by Ashtonio** [comment]
I tried that and it still only shows the basic browsers.
