### ISSUE TITLE
Feature request: Add "Web Search" option to the text selection menu

### ISSUE THREAD

**Issue by Astridchan** [chandevel/Clover#637]
In many apps (at least most of Google's apps) there is a "web search" option in the text selection menu when highlighting text, which will open a Google search for the selected text in the browser. This option is not there when selecting text in Clover. I find I'm often doing online searches on things I see when browsing 4chan on Clover, and such a feature would simplify that process (select text, copy, switch to browser, hit address bar, paste text, enter).

Here's an image that shows what I'm talking about:
![clover2](https://user-images.githubusercontent.com/40862101/53824419-93d1b700-3f7c-11e9-9ad5-a80b658a14ae.png)

**Comment by Adamantcheese** [comment]
[The current minimum API for Clover is 15, while the web search/floating text selection window is API 23 (Android 6.0/Marshmallow).](https://developer.android.com/reference/android/content/Intent.html#ACTION_PROCESS_TEXT) Floens would need to say if the API level could be raised before doing this.
