### ISSUE TITLE
Thread and settings backup and restore function

### ISSUE THREAD

**Issue by TacoTheDank** [chandevel/Clover#638]
https://github.com/Floens/Clover/pull/636#issuecomment-469944155

One feature that would be great to see is a thread and setting backup and restore function, like how the Reddit [Slide app](https://github.com/ccrama/Slide) does it (I believe [this](https://github.com/ccrama/Slide/blob/master/app/src/noGPlay/java/me/ccrama/redditslide/Activities/SettingsBackup.java) and [this](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/SettingValues.java) are the code files for this function). The data is stored in an xml file. Clover could easily have the same function with a little bit of code :)

**Comment by Adamantcheese** [comment]
[Settings are probably easy to do with this file.](https://github.com/Flowdalic/iesp/blob/master/iesp-aar/src/main/java/eu/geekplace/iesp/ImportExportSharedPreferences.java) I'm guessing thread backup you mean saved site/board/pin backup?

**Comment by TacoTheDank** [comment]
@Adamantcheese Yeah, as well as settings, since there are a lot.

**Comment by seniorm0ment** [comment]
Yeah I would love to see a way to backup and restore bookmarks/pins.
Some kind of auto sync feature option would be great as well.
